services:
  app:
    container_name: marketplace-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - marketplace-network
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_BASE_URL: 'http://localhost:8080'
      AUTH_TRUST_HOST: true
      AUTH_SECRET: '8cf9545ca93c4c5011f3dd2b348e6d66'
      AUTH_GITHUB_CLIENT_ID: 'Ov23li9ogKkhK6oszaIc'
      AUTH_GITHUB_CLIENT_SECRET: '1354294712d4b739107f6d77848b57222f1edb8f'
    restart: unless-stopped

networks:
  marketplace-network:
    external: true