services:
  app:
    container_name: marketplace-frontend-nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - marketplace-network
    restart: unless-stopped

networks:
  marketplace-network:
    external: true