services:
  app:
    container_name: marketplace-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - marketplace-network
    environment:
      NODE_ENV: 'production'
      NEXT_TELEMETRY_DISABLED: '1'
      NEXT_PUBLIC_BASE_URL: 'http://marketplace-backend-app:8080'
      NEXTAUTH_URL: 'http://localhost:3000'
      AUTH_TRUST_HOST: 'true'
      AUTH_SECRET: '8cf9545ca93c4c5011f3dd2b348e6d66'
      AUTH_GITHUB_CLIENT_ID: 'Ov23li9ogKkhK6oszaIc'
      AUTH_GITHUB_CLIENT_SECRET: 'c994ab85f6ae1dee4da6159a2d4c5fd1d7b80520'
    restart: unless-stopped

networks:
  marketplace-network:
    external: true
