apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-frontend-nextjs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-frontend-nextjs
  template:
    metadata:
      labels:
        app: marketplace-frontend-nextjs
    spec:
      containers:
        - name: nextjs
          image: thoggs/marketplace-frontend-nextjs:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "500Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NEXT_PUBLIC_BASE_URL
              value: "http://marketplace-backend-pod:8080"
            - name: AUTH_TRUST_HOST
              value: "true"
            - name: AUTH_SECRET
              value: "8cf9545ca93c4c5011f3dd2b348e6d66"
            - name: AUTH_GITHUB_ID
              value: "Ov23li9ogKkhK6oszaIc"
            - name: AUTH_GITHUB_SECRET
              value: "70662919b3db5cc0884105618f3c49fdadcafa8b"

---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-frontend-nextjs
  namespace: default
spec:
  type: NodePort
  selector:
    app: marketplace-frontend-nextjs
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000
