apiVersion: v1
kind: Pod
metadata:
  name: marketplace-frontend-pod
  labels:
    app: marketplace-frontend
spec:
  hostname: frontend-app
  containers:
    - name: app
      image: localhost/marketplace-frontend-nextjs:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
#      env:
#        - name: NODE_ENV
#          value: 'production'
#        - name: NEXT_TELEMETRY_DISABLED
#          value: "1"
#        - name: NEXT_PUBLIC_BASE_URL
#          value: "http://marketplace-backend-pod:8080"
#        - name: NEXTAUTH_URL
#          value: "http://localhost:3000"
#        - name: AUTH_TRUST_HOST
#          value: "FILL_FOR_KUBERNETS"
#        - name: AUTH_SECRET
#          value: "FILL_FOR_KUBERNETS"
#        - name: AUTH_GITHUB_CLIENT_ID
#          value: "FILL_FOR_KUBERNETS"
#        - name: AUTH_GITHUB_CLIENT_SECRET
#          value: "FILL_FOR_KUBERNETS"
      resources:
        requests:
          memory: "500Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
  restartPolicy: Always


# podman build --rm --layers=false -t marketplace-frontend-nextjs:latest . && podman play kube pod.yml