apiVersion: v1
kind: Pod
metadata:
  name: marketplace-frontend-pod
  labels:
    app: marketplace-frontend
spec:
  hostname: frontend-app
  containers:
    - name: app
      image: localhost/marketplace-frontend-nextjs:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
      env:
        - name: NODE_ENV
          value: production
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: NEXT_PUBLIC_BASE_URL
          value: "http://marketplace-backend-pod:8080"
        - name: AUTH_TRUST_HOST
          value: "true"
        - name: AUTH_SECRET
          value: "Xk9kG5R2fI2r2fYjqM3OUClnHQB3igtEqXv2NdpzHrY="
        - name: AUTH_GITHUB_ID
          value: "Ov23li9ogKkhK6oszaIc"
        - name: AUTH_GITHUB_SECRET
          value: "1354294712d4b739107f6d77848b57222f1edb8f"
      resources:
        requests:
          memory: "500Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
  restartPolicy: Always


# podman build -t marketplace-frontend-nextjs:latest . && podman play kube pod.yml